name: econo-recruit-local

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0.13
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

  axon-server:
    image: axoniq/axonserver:4.6.11
    container_name: axon-server
    restart: unless-stopped
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axon-data:/axonserver/data
      - axon-events:/axonserver/events
      - axon-config:/axonserver/config

volumes:
  mysql-data:
  mongo-data:
  redis-data:
  axon-data:
  axon-events:
  axon-config:
