version: "3.7"
services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    network_mode: "host"

  axon-server:
    image: axoniq/axonserver:4.6.11
    container_name: axon-server
    restart: unless-stopped
    ports:
      - "8024:8024"
      - "8124:8124"

  backend:
    image: blackbean99/econo-recruit:latest
    restart: unless-stopped
    container_name: backend
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - axon-server

  nginx:
    image: nginx:1.21.5-alpine
    container_name: myweb-proxy
    network_mode: "host"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/ssl
    depends_on:
      - backend