plugins {
    id 'java'
    id 'com.google.cloud.tools.jib' version '3.5.3'
    id "org.asciidoctor.jvm.convert" version "3.3.2"
}

group = 'com.jnu'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

configurations {
    asciidoctorExtensions
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    testImplementation 'junit:junit:4.13.1'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    // GraphQL
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation 'com.graphql-java:graphql-java-extended-scalars:19.1'
    testImplementation 'org.springframework.graphql:spring-graphql-test'


    // websocket client
    implementation 'org.webjars:webjars-locator-core'
    implementation 'org.webjars:sockjs-client:1.0.2'
    implementation 'org.webjars:stomp-websocket:2.3.3'
    implementation 'org.webjars:bootstrap:3.3.7'
    implementation 'org.webjars:jquery:3.1.1-1'
    // XSS validator
    implementation 'org.jsoup:jsoup:1.13.1'
    // json
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.17'
    //    testImplementation 'org.junit.jupiter:junit-jupiter-api:4.13'
    //    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    // statemachine
    implementation 'org.springframework.statemachine:spring-statemachine-core:4.0.0'
    implementation project(':Recruit-Common')
    implementation project(':Recruit-Domain')
    implementation project(':Recruit-Infrastructure')

    // quartz-scheduler
    implementation("org.springframework.boot:spring-boot-starter-quartz")

    testRuntimeOnly 'com.h2database:h2'
}

jib {
    def serverPort = "8080"
    def dockerUsername = System.getenv("DOCKERHUB_USERNAME")
    def dockerPassword = System.getenv("DOCKERHUB_PASSWORD")
    def imageName = System.getenv("IMAGE_NAME") ?: "blackbean99/econo-recruit"
    def imageTag = System.getenv("IMAGE_TAG") ?: "latest"

    from {
        image = 'amazoncorretto:25-alpine-jdk'
    }
    to {
        image = imageName
        tags = [imageTag]
        auth { // docker auth
            username = dockerUsername ? dockerUsername : ""
            password = dockerPassword ? dockerPassword : ""
        }
    }
    container {
        jvmFlags = [
                '-Dspring.profiles.active=' + (System.getenv("ACTIVE_PROFILE") ?: "local"),
                '-Dserver.port=' + serverPort,
                '-Xms2G', '-Xmx2G',
                '-XX:+UseG1GC',
                '-XX:+UseContainerSupport',
                '-XX:+DisableExplicitGC',
                '-server'
        ]
        ports = ['8080']
    }
    ext {
        // snippetsDir : 테스트 실행시 생성되는 응답을 저장할 디렉토리 지정
        set('snippetsDir', file("build/generated-snippets"))
    }

// === ⭐ Spring Rest Docs ===
    tasks.named('test') {
        systemProperty 'file.encoding', 'UTF-8'
        outputs.dir snippetsDir
        useJUnitPlatform()
    }

// (7) asciidoctor를 사용하기 위해서 asciidoctor task에 asciidoctorExtensions 설정
    tasks.named('asciidoctor') {
        configurations "asciidoctorExtensions"
        inputs.dir snippetsDir
        dependsOn test
    }

// (8) asciidoctor task 실행시 생성된 html 파일을 src/main/resources/static/docs 디렉토리에 카피
    task copyDocument(type: Copy) {
        dependsOn asciidoctor            // (8-1)
        from file("${asciidoctor.outputDir}")   // (8-2)
        into file("src/main/resources/static/docs")   // (8-3)
    }

    build {
        dependsOn copyDocument  // (9) 빌드되기전 copyDocument task 실행
    }

// (10)2121
    bootJar {
        dependsOn copyDocument    // (10-1) bootJar 실행되기전 copyDocument task 실행
        from("${asciidoctor.outputDir}") {  // (10-2) bootJar에 asciidoctor task에서 생성된 html 파일 추가
            into 'static/docs'     // (10-3) bootJar에 추가될 경로
        }
        enabled = false
    }
    jar.enabled = true
}
