spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
data:
  init:
    disabled: ${DATA_INIT_DISABLED:false}
    admin:
      id: ${ADMINISTRATOR_ID:admin}
      password: ${ADMINISTRATOR_PASSWORD:password}
server:
  port: ${SERVER_PORT:10023}
throttle:
  greedyRefill: ${THROTTLE_GREEDY_REFILL:10}
  overdraft: ${THROTTLE_OVERDRAFT:10}
auth:
    blacklist:
      prefix: ${JWT_BLACKLIST_PREFIX:BlackList_AccessToken_}
logging:
  level:
    root: WARN
login:
  page:
    url: ${LOGIN_PAGE_URL:http://localhost:8080/login}
    success:
      url: ${LOGIN_SUCCESS_URL:http://localhost:8080/loginSuccess}
    failure:
      url: ${LOGIN_FAILURE_URL:http://localhost:8080/loginFailure}
acl:
  whiteList: ${ACL_WHITE_LIST:localhost}
axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_SERVER_HOST:127.0.0.1:8124}
springdoc:
  version: v1
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
#  packages-to-scan: com.econovation.recruit
  path-to-match: /api/**
  swagger-ui:
#    path: /swagger-ui.html
    tags-sorter: alpha
#    url: /swagger-ui.html
    display-query-params: true
    version: ${SWAGGER_VERSION:0.0.1-SNAPSHOT}
  api-docs:
    path: /api-docs
    groups:
      enabled: true
    model-and-view-attribute:
      enabled: true

swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}
  version: ${RECRUIT_SWAGGER_VERSION:0.0.1-SNAPSHOT}
mail:
  destination:
    url: ${MAIL_DESTINATION_URL:http://localhost:8080}
econovation:
  year: ${ECONOVATION_YEAR:27}
  recruit:
    period:
      start: ${RECRUIT_PERIOD_START:2024-03-04T00:00:00}
      end: ${RECRUIT_PERIOD_END:2024-03-15T23:59:59}
      passedDate: ${RECRUIT_PERIOD_PASSED_DATE:2024-03-18T09:00:00}
    valid:
      enabled: ${RECRUIT_PERIOD_ENABLED:false}
    admin:
      email: ${RECRUIT_ADMIN_EMAIL:email@gmail.com}
notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
  slack:
    enabled: ${NOTIFICATION_SLACK_ENABLED:true}
---
spring:
  config:
    activate:
      on-profile: local
#logging:
#  level:
#    root: info
#logging:
#  level:
#    org.springframework.data.*.*: debug
#    org.springframework.cache.*: debug
---
spring:
  config:
    activate:
      on-profile: dev

# DEBUG log level
logging:
  level:
    root: WARN
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    ROOT: WARN
---
spring:
  config:
    activate:
      on-profile: test
