spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
throttle:
  greedyRefill: ${THROTTLE_GREEDY_REFILL:10}
  overdraft: ${THROTTLE_OVERDRAFT:10}
auth:
  jwt:
    blacklist:
      prefix: ${JWT_BLACKLIST_PREFIX:BlackList_AccessToken_}
login:
  page:
    url: ${LOGIN_PAGE_URL:http://localhost:8080/login}
    success:
      url: ${LOGIN_SUCCESS_URL:http://localhost:8080/loginSuccess}
    failure:
      url: ${LOGIN_FAILURE_URL:http://localhost:8080/loginFailure}
acl:
  whiteList: ${ACL_WHITE_LIST:localhost}

springdoc:
  version: v1
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.econovation.recruit
  path-to-match: /api/**
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    url: /swagger-ui.html
    display-query-params: true
    groups:
      enabled: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
    model-and-view-attribute:
      enabled: true

swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}
  version: ${WHATNOW_VERSION:0.0.1-SNAPSHOT}
mail:
  destination:
    url: ${MAIL_DESTINATION_URL:http://localhost:8080}
---
spring:
  config:
    activate:
      on-profile: local
#logging:
#  level:
#    root: info
#logging:
#  level:
#    org.springframework.data.*.*: debug
#    org.springframework.cache.*: debug
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    ROOT: WARN