spring:
  threads:
    virtual:
      enabled: true
  profiles:
    include:
      - infrastructure
      - domain
      - common
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  quartz:
    jdbc:
      initialize-schema: always
      schema: classpath:quartz-init.sql
    job-store-type: jdbc
    overwrite-existing-jobs: true
  graphql:
    path: /api/graphql
    schema:
      locations: classpath:graphql/**/
data:
  init:
    disabled: ${DATA_INIT_DISABLED:false}
    admin:
      id: ${ADMINISTRATOR_ID:admin}
      password: ${ADMINISTRATOR_PASSWORD:password}
server:
  port: ${SERVER_PORT:10023}
throttle:
  greedyRefill: ${THROTTLE_GREEDY_REFILL:10}
  overdraft: ${THROTTLE_OVERDRAFT:10}
auth:
    blacklist:
      prefix: ${JWT_BLACKLIST_PREFIX:BlackList_AccessToken_}
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.quartz: ${QUARTZ_LOG_LEVEL:INFO}
    org.springframework.scheduling.quartz: ${QUARTZ_LOG_LEVEL:INFO}

login:
  page:
    url: ${LOGIN_PAGE_URL:http://localhost:8080/login}
    success:
      url: ${LOGIN_SUCCESS_URL:http://localhost:8080/loginSuccess}
    failure:
      url: ${LOGIN_FAILURE_URL:http://localhost:8080/loginFailure}
acl:
  whiteList: ${ACL_WHITE_LIST:localhost}
axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_SERVER_HOST:127.0.0.1:8124}
springdoc:
  version: v1
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
#  packages-to-scan: com.econovation.recruit
  path-to-match: /api/**
  swagger-ui:
    tags-sorter: alpha
    display-query-params: true
    version: ${SWAGGER_VERSION:0.0.1-SNAPSHOT}
    path: /swagger-ui
  api-docs:
    path: /api-docs
    groups:
      enabled: true
    model-and-view-attribute:
      enabled: true

swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}
  version: ${RECRUIT_SWAGGER_VERSION:0.0.1-SNAPSHOT}
mail:
  destination:
    url: ${MAIL_DESTINATION_URL:http://localhost:8080}
econovation:
  year: ${ECONOVATION_YEAR:28}
  domain: ${ECONOVATION_DOMAIN:recruit.econovation.kr}
  file:
    path:
      portfolio: ${ECONOVATION_PORTFOLIO_PATH:server/portfolio.pdf}
  recruit:
    period:
      passedDate: ${RECRUIT_PERIOD_PASSED_DATE:2025-03-14T09:00:00}
      firstDiscussion: ${RECRUIT_PERIOD_FIRST_DISCUSSION:2025-03-14T08:00:00}
      finalDiscussion: ${RECRUIT_PERIOD_FINAL_DISCUSSION:2025-03-24T08:00:00}
      finalDiscussionCron: ${RECRUIT_PERIOD_FINAL_DISCUSSION_CRON:0 0 9 24 3 ?}
    valid:
      enabled: ${RECRUIT_PERIOD_ENABLED:false}
    admin:
      email: ${RECRUIT_ADMIN_EMAIL:email@gmail.com}
    open_chat_url: ${OPEN_CHAT_URL:https://recruit.econovation.kr}
    open_chat_url_deadline: ${OPEN_CHAT_URL_DEADLINE:2025-03-15T23:59:59}
    ot_receive_url: ${ORIENTATION_RECEIVE_URL:https://recruit.econovation.kr}
    ot_schedule: ${ORIENTATION_DATE:2025-03-27T17:00:00}
    ot_place: ${ORIENTATION_PLACE:전남대학교 정보화본부 109호}

notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
  slack:
    enabled: ${NOTIFICATION_SLACK_ENABLED:true}
---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.springframework.graphql: debug
#logging:
#  level:
#    org.springframework.data.*.*: debug
#    org.springframework.cache.*: debug
---
spring:
  config:
    activate:
      on-profile: dev

# DEBUG log level
logging:
  level:
    root: WARN
---
spring:
  config:
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
logging:
  level:
    ROOT: WARN

econovation:
  file:
    path:
      portfolio: ${ECONOVATION_PORTFOLIO_PATH:/app/resources/static/mail/portfolio.pdf}
---
spring:
  config:
    activate:
      on-profile: test
