name: 서비스 빌드
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      spring-profile-active:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

env:
  IMAGE_TAG: ${{ inputs.image-tag || 'latest' }}
  ACTIVE_PROFILE: ${{ inputs.spring-profile-active || 'local' }}
  IMAGE_NAME: ${{ inputs.image-name }}

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 애드온 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }
          MONGO_URI: ${{ secrets.MONGO_URI}}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}

        run: |
          echo "IMAGE_TAG=$IMAGE_TAG, ACTIVE_PROFILE=$ACTIVE_PROFILE, IMAGE_NAME=$IMAGE_NAME" &&
          chmod +x ./server/gradlew &&
          .server/gradlew jib
