name: 'spotless & Sonar analyze'

on:
  workflow_call:
    # secrets:
    # SONAR_TOKEN:
    #   required: true

jobs:
  spotless-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 애드온 준비
        uses: gradle/gradle-build-action@v2

      - name: Spotless Check
        run: |
          cd ./server
          ./gradlew spotlessCheck
          cd ..

      - name: SonarCloud scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ./server
          ./gradlew sonar --info --stacktrace
          cd ..

