name: 서비스 배포

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true
      SSH_PORT:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      spring-profile-active:
        required: true
        type: string
      image-name:
        required: true
        type: string
      service-name:
        required: true
        type: string

env:
  IMAGE_TAG: 'latest'
  ACTIVE_PROFILE: ${{ inputs.spring-profile-active || 'local' }}
  ENVIRONMENT: ${{ inputs.environment || 'local' }}

jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    name: 서비스 배포하기
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: 배포 스크립트 실행
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./econo-recruit/server
            # Remove origin was container 
            docker rm -f backend
            # Pull and Deploy new built docker image with new tag
            docker pull blackbean99/econo-recruit:latest
            docker-compose up -d --remove-orphans
            docker image prune -a -f


#      - name: 배포 완료 슬랙 알림 보내기
#        uses: 8398a7/action-slack@v3
#        with:
#          status: custom
#          fields: author, workflowRun, pullRequest
#          custom_payload: |
#            {
#              attachments: [{
#                color: '#59f764',
#                title: '서버 배포 알림',
#                text: `Econo-Recruit 서버 배포 성공!`,
#                fields: [
#                  {
#                    title: '배포 환경',
#                    value: `${process.env.ENVIRONMENT}`,
#                    short: true,
#                  },
#                  {
#                    title: '배포자',
#                    value: `${process.env.AS_AUTHOR}`,
#                    short: true,
#                  },
#                  {
#                    title: '워크플로 링크',
#                    value: `${process.env.AS_WORKFLOW_RUN}`,
#                    short: true,
#                  },
#                  {
#                    title: 'PR 링크',
#                    value: `${process.env.AS_PULL_REQUEST}`,
#                    short: true,
#                  }
#                ]
#              }]
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 배포 완료 디스코드 알림 보내기
        run: |
          curl -X
          POST -H 'Content-type:application/json'
          -d "$DATA"
          ${{ secrets.DISCORD_WEBHOOK_URL }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DATA: |
        DATA: |
        {
        "username" : "🔔배포 알리미🔔",
        "avatar_url" : "https://i.namu.wiki/i/X6s5AIfkjae-h54b7EkMYVg7ityFni1B-YIhtck0g6P914sJTsjykJDEbrsoZdV8rmwmrcyioAH3d2CxLmjxLx20dpHZI1izwMjfs7Dvtuchchyt2HDu7iQyy02_QaU6b8RrxWBt4G0PMQ0IZTykpQ.webp",
        "embeds" : [
          {
            "title" : "배포가 성공했어요~",
            "type" : "rich",
            "color" : "123456",
            "author" : {
              "name" : "칠가이",
              "icon_url" : "https://i.namu.wiki/i/X6s5AIfkjae-h54b7EkMYVg7ityFni1B-YIhtck0g6P914sJTsjykJDEbrsoZdV8rmwmrcyioAH3d2CxLmjxLx20dpHZI1izwMjfs7Dvtuchchyt2HDu7iQyy02_QaU6b8RrxWBt4G0PMQ0IZTykpQ.webp"
            },
            "fields" : [
              {
                "name": "커밋 메시지",
                "value": "'$(git log -1 --pretty=%B)'",
                "inline": false
              },
              {
                "name": "브랜치",
                "value": "'${{ github.ref }}'",
                "inline": true
              },
              {
                "name": "배포 환경",
                "value": "`Prod`",
                "inline": true
              },
              {
                "name": "GitHub Actions",
                "value": "[배포 워크플로우 실행 확인](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                "inline": false
              }
            ],
            "footer": {
              "text": "배포 시각",
              "icon_url": "https://cdn-icons-png.flaticon.com/512/25/25231.png"
            },
            "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
          }
        ]
        }

